name: Build and deploy to Tktech-AKS
on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      run-options:
        description: 'Select run-options. (mandatory)'
        required: true
        default: 'run-app'
        type: choice
        options:
        - run-app

env:
  APP_IMAGE: ghcr.io/mehmetkanus17/kubernetes-logs/logs-app
  REGISTRY: ghcr.io
  NAMESPACE: logs

jobs:
  build-app:
    if: inputs.run-options == 'run-app' || contains(github.event.head_commit.message, 'run-app')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout original repository
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.APP_IMAGE }}
          tags: |
            ${{ github.sha }}
            latest

      - name: login GHCR (github container registry)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images
        id: push
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

# CD kısmını kendi yapılandırmanıza göre ister cd stage'inden ister gitops üzerinden uygulayabilirsiniz.